import { FR_COUNTRY_NAMES, FR_LANGUAGE_NAMES } from "../../lib/countryMapping";
export const frTranslation = {
  translation: {
    common: {
      loading: "Chargement…",
      refresh: "↻ Rafraîchir",
      none: "— Aucun",
      allStatuses: "Tous statuts",
      status: {
        pending: "En attente",
        validated: "Validé",
        refused: "Refusé",
        review: "À revoir",
        selected: "Sélectionné",
      },
      badges: {
        grand_prix: "Grand Prix",
        prix_jury: "Prix du Jury",
      },
      yes: "Oui",
      no: "Non",
      cancel: "Annuler",
      delete: "Supprimer",
      save: "Sauvegarder",
      saving: "Sauvegarde…",
      search: "Rechercher…",
      back: "Retour",
      next: "Suivant",
      previous: "Précédent",
      error: "Erreur",
    },
    nav: {
      submit: "Soumettre",
      catalogue: "Catalogue",
      palmares: "Palmarès",
      panel: "Panel",
      jury: "Jury",
      dashboard: "Dashboard",
      jurySpace: "Jury",
      setup: "Setup requis",
      sessionActive: "Session active",
      secureAccess: "Session active · Accès sécurisé",
      statusOpen: "SYS:MARS_AI_2026 // STATUS:OPEN",
      festival: "FESTIVAL",
      tabs: {
        films: "Films",
        users: "Utilisateurs",
        site: "Site",
        partners: "Partenaires",
        youtube: "YouTube",
        email: "Emails",
      },
      stats: {
        films: "Films",
        selected: "Sélectionnés",
        pending: "En attente",
        validated: "Validés",
        review: "À revoir",
        refused: "Refusés",
        progress: "Progression",
        done: "✓ Terminé",
      },
    },
    meta: {
      home: "Accueil",
      jury: "Espace Jury",
      panel: "Panel Admin",
      notFound: "Page introuvable",
    },
    notFound: {
      eyebrow: "NAVIGATION · ERREUR",
      title: "404",
      subtitle: "Cette page n’existe pas.",
      message: "Le lien est peut-être incorrect, ou la page a été déplacée.",
      backHome: "Retour à l’accueil",
      seeCatalogue: "Voir le catalogue",
    },
    auth: {
      google: "Se connecter avec Google",
      footerPrefix: "MARS",
      footerAccent: "AI",
      footerSuffix: " · Festival 2026",
    },
    home: {
      eyebrow: "APPEL À FILMS OUVERT",
      eyebrowClosed: "APPEL À FILMS FERMÉ",
      eyebrowSuffix: "· MARSEILLE 2026",
      terminal: "> FESTIVAL_IA_V1.0 // INITIATING{{cursor}}",
      title1: "IMAGINEZ",
      title2: "DES FUTURS",
      title3: "SOUHAITABLES",
      heroText:
        "Courts-métrages {{duration}} entièrement générés par {{ai}}. Ouvert à tous. Sans inscription.",
      duration: "1–2 min",
      ai: "intelligence artificielle",
      ctaSubmit: "SOUMETTRE UN FILM",
      ctaCatalogue: "VOIR LE CATALOGUE",
      phaseNoticePhase2: "INSCRIPTIONS TERMINÉES · DÉBUT PHASE 2",
      phaseNoticePhase3: "LES JURYS ONT VOTÉ · DÉBUT DE LA PHASE 3",
      phaseNoticePalmares:
        "LE GRAND PRIX A ÉTÉ DÉCERNÉ · MERCI D'AVOIR PARTICIPÉ",
      timeline: "TIMELINE · FESTIVAL 2026",
      phaseLabel: "{{phase}} // ACTIVE",
      dateTbd: "> DATE_TBD",
      countdown: {
        closed: "> SUBMISSIONS_CLOSED",
        days: "Jours",
        hours: "Heures",
        minutes: "Min",
        seconds: "Sec",
      },
      stats: {
        countries: "PAYS",
        filmsExpected: "FILMS ATTENDUS",
        visitors: "VISITEURS",
      },
      statsNumbers: {
        countries: "120",
        filmsExpected: "600",
        visitors: "3000",
      },
      phases: {
        p1Title: "APPEL À FILMS",
        p1Desc: "1–2 min · 100% IA · International",
        p2Title: "SÉLECTION OFFICIELLE",
        p2Desc: "50 films retenus par le jury",
        p3Title: "PALMARÈS",
        p3Desc: "Grand Prix · Prix du Jury · Prix du Public",
      },
      place: "LA PLATEFORME × MOBILE FILM FESTIVAL",
      featureTitle1: "L'IA au service",
      featureTitle2: "de la création cinématographique",
      featureText:
        "marsAI place l'humain au cœur de la création assistée par IA. Stimulez votre créativité via le format court et rejoignez une communauté internationale autour de l'IA générative.",
      featureCta: "SOUMETTRE",
      palmaresCta: "PALMARÈS →",
      featureTags: [
        "1–2 minutes",
        "IA générative",
        "Sans inscription",
        "International",
        "Multi-films",
        "Sous-titres",
      ],
      scroll: "SCROLL",
      live: "EN COURS",
      finished: "TERMINÉ",
      themeTitle: "THÈME 2026",
      themeQuote: '"IMAGINEZ DES\nFUTURS SOUHAITABLES"',
    },
    catalogue: {
      eyebrow: "SÉLECTION OFFICIELLE · FESTIVAL MARSAI 2026",
      title: "Catalogue",
      subtitle:
        "{{count}} films sélectionnés · {{perPage}} par page · Imaginez des futurs souhaitables",
      error: "Erreur",
      aiTools: "Outils IA :",
      videoUnavailable: "Vidéo indisponible",
      pageLabel: "{{page}}/{{total}} · {{count}} films",
      rangeLabel: "Films {{from}}–{{to}} sur {{total}}",
    },
    palmares: {
      eyebrow: "marsAI 2026 · Marseille · Résultats officiels",
      title: "Palmarès",
      subtitle:
        "{{total}} films · {{laureats}} lauréats · Festival marsAI 2026",
      error: "Erreur",
      grandPrix: "Grand Prix",
      specialPrizes: "Prix du Jury",
      mentions: "Prix du Jury",
      selection: "Prix du Jury · {{count}} films",
      selectionLess: "↑ Réduire",
      selectionMore: "↓ Voir les {{count}} autres films",
      footer1: "La Plateforme × Mobile Film Festival · Marseille 2026",
      footer2: "Festival marsAI · Courts-métrages entièrement générés par IA",
      videoUnavailable: "Vidéo indisponible",
    },
    jury: {
      loginEyebrow: "Accès restreint · Jury",
      loginTitle: "Espace Jury",
      loginSubtitle1: "MARSAI · Festival 2026",
      loginSubtitle2: "Authentification Google requise.",
      assigned: "{{count}} films assignés",
      voted: "Validés",
      remaining: "À revoir",
      refused: "Refusés",
      searchPlaceholder: "Rechercher…",
      filterVotedSearch: "Votés",
      filterRemaining: "À revoir",
      filterAll: "Tous",
      filterPending: "À revoir",
      filterVoted: "Votés",
      noFilm: "Aucun film",
      loading: "Chargement des films…",
      noResultsTitle: "Aucun résultat",
      noResultsDesc: "Aucun film ne correspond à votre recherche ou filtre.",
      noAssignedTitle: "Aucun film assigné",
      noAssignedDesc:
        "Le panel admin doit vous assigner des films avant que vous puissiez voter.",
      selectFilm: "Sélectionner un film",
      noVideo: "Aucune vidéo liée à ce film",
      votedStatus: "✓ Validé",
      pendingStatus: "À voter",
      voteTitle: "Mon vote",
      actions: {
        validate: "Valider",
        refuse: "Refuser",
        review: "À revoir",
      },
      commentLabel: "Commentaire",
      commentOptional: "(optionnel)",
      commentRequired: "Un commentaire est requis pour un refus.",
      commentPlaceholder: "Votre commentaire…",
      refusePlaceholder: "Motif du refus obligatoire…",
      nextFilm: "Film suivant",
      sendVote: "Envoyer le vote",
      voteLocked: "Vote verrouillé",
      voteAlreadySubmitted: "Vote déjà envoyé, modification impossible.",
      updateVote: "Modifier le vote",
      voteSuccess: "Vote envoyé avec succès",
      voteError: "Erreur lors de l'envoi du vote.",
      submitting: "Envoi…",
      sending: "Envoi…",
    },
    panel: {
      loginEyebrow: "Accès restreint · Panel",
      loginTitle: "Panel Admin",
      loginSubtitle1: "MARSAI · Festival 2026",
      loginSubtitle2: "Authentification Google requise.",
      filmsSearch: "Rechercher par titre, réalisateur, pays ou ID…",
      assignTo: "Assigner exclusivement à :",
      assign: "Assigner",
      assigning: "Assignation…",
      cancel: "Annuler",
      selectedCount: "{{count}} film(s) sélectionné(s)",
      selectedTitle: "Sélection officielle",
      selectedCountLabel: "{{count}} / 50",
      listFooter: "{{shown}} film(s) affichés sur {{total}} total",
      noFilms: "Aucun film",
      noFilmsHelp: "Modifier la recherche ou le filtre",
      votes: "Votes",
      juryAssigned: "Jury assigné",
      status: "Statut",
      badge: "Badge",
      view: "Voir ↗",
      publish: "Publier",
      none: "—",
      welcome: {
        title: "Configuration initiale du panel",
        description:
          "Avant de continuer, renseignez l’URL de la plateforme et l’email expéditeur Brevo.",
        stepsTitle: "Étapes recommandées",
        stepDomain: "Définissez l’URL de votre nom de domain.",
        stepBrevo:
          "Renseignez l’email expéditeur Brevo pour les confirmations et décisions.",
        stepSiteTab:
          "Validez puis poursuivez les réglages détaillés dans les onglets Site et Emails.",
        urlRequired: "Renseignez l’URL de la plateforme.",
        emailRequired: "Renseignez l’email Brevo expéditeur.",
        skip: "Plus tard",
        save: "Enregistrer la configuration",
        saving: "Enregistrement…",
        savedTitle: "Configuration initiale enregistrée",
        savedDescription:
          "Vous pouvez maintenant continuer la configuration du festival.",
      },
      users: {
        title: "Nouveau membre",
        fullName: "Nom complet",
        fullNamePlaceholder: "Prénom Nom",
        email: "Email",
        emailPlaceholder: "email@domain.com",
        role: "Rôle",
        roles: {
          admin: "Admin",
          moderator: "Modérateur",
          jury: "Jury",
        },
        columns: {
          name: "Nom",
          email: "Email",
          role: "Rôle",
          google: "Google",
        },
        count: "{{count}} membre(s)",
        inviteHint: "Un email d'invitation sera envoyé automatiquement.",
        create: "Créer le compte",
        creating: "Création…",
        refresh: "Rafraîchir",
        search: "Rechercher…",
        none: "Aucun membre",
        googleConnected: "● Connecté",
        googleUnlinked: "○ Non lié",
        deleteTitle: "Supprimer ce membre ?",
        deleteDesc: "Cette action est définitive.",
        delete: "Supprimer",
        deleting: "Suppression…",
      },
      site: {
        editorTitle: "Éditeur du site",
        editorHint: "Organisation compacte par section",
        sections: {
          home: "Home",
          submission: "Soumission",
          festival: "Festival",
        },
        phasesTitle: "Dates des phases",
        phasesHint: "Dates de transition entre les phases du festival",
        editorialTitle: "Contenu éditorial",
        editorialHint: "Textes et visuels affichés sur le site public",
        optionsTitle: "Options soumission",
        optionsHint:
          "Édition simplifiée des listes + JSON pour réseaux sociaux",
        optionsCompactHint:
          "Éditez une liste à la fois pour garder un écran court",
        homeTextTitle: "Textes Home",
        homeTextHint:
          "Modifiez à la volée les contenus FR/EN de la page d’accueil",
        socialsHint: "Réseaux proposés dans le formulaire de soumission",
        socialKey: "Identifiant",
        socialLabel: "Libellé affiché",
        previewTitle: "Aperçu en direct",
        previewHint: "Prévisualisation des modifications avant sauvegarde",
        previewIframeHint: "Rendu Home réel avec vos brouillons en direct",
        previewBadge: "aperçu",
        previewNoDescription: "Description du festival",
        previewFooterFallback: "© marsAI",
        previewFormTitle: "Aperçu du formulaire",
        previewFormHint: "Extraits des choix visibles par les participants",
        previewEmpty: "Aucune option",
        currentTitle: "Valeurs actuelles",
        noData: "Aucune donnée chargée.",
        save: "Sauvegarder",
        saving: "Sauvegarde…",
        refresh: "Rafraichir",
        languageFr: "Français",
        languageEn: "Anglais",
        editingInProgress: "Édition en cours :",
        selectAll: "Tout cocher",
        clearAll: "Tout décocher",
        festivalKeywordsTitle: "Mots-clés de la section festival",
        phaseMeta: {
          submissionClose: "Clôture des soumissions",
          catalogueOpen: "Ouverture catalogue",
          palmares: "Palmarès",
        },
        homeFieldLabels: {
          eyebrow: "Bandeau d'introduction",
          terminal: "Texte style terminal",
          title1: "Titre principal — ligne 1",
          title2: "Titre principal — ligne 2",
          title3: "Titre principal — ligne 3",
          heroText: "Texte d'introduction",
          ctaSubmit: "Bouton phase 1 (Soumettre)",
          ctaCatalogue: "Bouton phase 2 (catalogue)",
          timeline: "Titre de la frise",
          themeTitle: "Titre du thème",
          themeQuote: "Citation du thème",
          featureTitle1: "Titre section festival — ligne 1",
          featureTitle2: "Titre section festival — ligne 2",
          featureText: "Description section festival",
          featureCta: "Action section festival",
          palmaresCta: "Bouton phase 3 (palmarès)",
          place: "Lieu du festival",
          statsCountries: "Statistique — Pays",
          statsFilmsExpected: "Statistique — Films attendus",
          statsVisitors: "Statistique — Visiteurs",
        },
        phase1: "Phase 1 · Clôture",
        phase2: "Phase 2 · Catalogue",
        phase3: "Phase 3 · Palmarès",
        selectDate: "Sélectionner une date",
        selectHour: "Heure",
        selectMinute: "Minute",
        timeHour: "{{value}} h",
        timeMinute: "{{value}} min",
        logo: "Nom / Logo",
        hero: "URL image Hero",
        platformBaseUrl: "URL plateforme",
        description: "Description festival",
        jsonFields: {
          categories: "Catégories",
          languages: "Langues",
          countries: "Pays",
          jobs: "Métiers",
          discovery: "Sources découverte",
          aiTools: "Outils IA",
          tags: "Tags sémantiques",
          socials: "Réseaux sociaux",
        },
        placeholders: {
          logo: "marsAI 2026",
          hero: "https://…",
          platformBaseUrl: "marsai.192.168.10.10.nip.io:4001",
          description: "Festival de courts-métrages IA…",
          jsonArray: '["valeur1","valeur2"]',
          optionItem: "Nouvelle option…",
          categories: "Ex : Fiction",
          languages: "Ex : Français",
          countries: "Ex : France",
          jobs: "Ex : Réalisateur",
          discovery: "Ex : Instagram",
          aiTools: "Ex : Runway",
          tags: "Ex : Futur souhaitable",
          socialKey: "instagram",
          socialLabel: "Instagram",
        },
        addOption: "Ajouter",
        removeOption: "Retirer",
        emptyOptions: "Aucune option",
        optionsRecovered:
          "JSON invalide détecté, la liste est réinitialisée localement.",
        jsonInvalid: "{{label}} : JSON invalide",
        arrayRequired: "{{label}} : tableau requis",
        socialsInvalidJson: "Réseaux sociaux : JSON invalide",
        socialsArrayRequired: "Réseaux sociaux : tableau requis",
        saved: "Réglages sauvegardés",
      },
      partners: {
        title: "Logos partenaires",
        subtitle: "Upload images · PNG/JPG/WebP/SVG/GIF · 5 Mo max",
        reset: "Réinitialiser",
        upload: "Uploader",
        uploading: "Upload…",
        files: "{{count}} fichier(s) sélectionné(s)",
        pickFiles: "Cliquez pour sélectionner des logos",
        formatsHint: "PNG, JPG, SVG, WebP — fonds transparents recommandés",
        multiSelectHint:
          "Vous pouvez sélectionner plusieurs fichiers à la fois",
        online: "Logos en ligne",
        json: "Aperçu JSON",
        empty: "Aucun logo",
        count: "{{count}} logo(s)",
        added: "Logos ajoutés",
        removed: "Logo supprimé",
        partnerAlt: "Logo partenaire",
        partnerDefault: "Partenaire",
        ok: "OK",
        deleteTitle: "Supprimer ce logo ?",
        deleteDesc: "Le fichier sera supprimé du serveur.",
        editLink: "Lien",
        editLinkTitle: "Lien du partenaire",
        editLinkDesc:
          "Ajoutez un lien de redirection pour ce logo (optionnel).",
        linkPlaceholder: "https://site-partenaire.com",
        linkHint: "Laissez vide pour supprimer le lien.",
        linkInvalid: "URL partenaire invalide.",
        linkSaved: "Lien partenaire enregistré",
      },
      youtube: {
        title: "Chaîne YouTube",
        subtitle: "Paramètres de vérification copyright et pipeline vidéo",
        channelId: "ID chaîne YouTube",
        channelIdPlaceholder: "UCxxxxxxxxxxxxxxxxxxxxxx",
        channelName: "Nom de la chaîne",
        channelNamePlaceholder: "marsAI Private Review",
        connect: "Connecter la chaîne",
        connecting: "Connexion…",
        disconnect: "Déconnecter",
        disconnectChannel: "Déconnecter la chaîne",
        disconnecting: "Déconnexion…",
        connected: "Chaîne connectée",
        disconnected: "Chaîne non connectée",
        defaultPrivacy: "Visibilité par défaut",
        privacy: {
          private: "Privée",
          unlisted: "Non répertoriée",
          public: "Publique",
        },
        autoCheck: "Lancer automatiquement le check copyright YouTube",
        moveToS3AfterCheck: "Copier sur S3 seulement après validation YouTube",
        workflowTitle: "Workflow recommandé",
        workflowHint: "Ordre de traitement conseillé pour les soumissions",
      },
      email: {
        title: "Campagnes emails",
        headerDescription: "Modèles d'e-mails envoyés aux porteurs de projets",
        senderEmail: "Email expéditeur Brevo",
        senderDescription:
          "Adresse utilisée pour tous les envois automatiques depuis la plateforme",
        submissionTemplate: "Confirmation de soumission",
        submissionDescription:
          "Envoyé automatiquement à la réception d'un projet",
        submissionHint:
          "Variables disponibles : {{directorName}}, {{filmTitle}}, {{submissionId}}",
        decisionTemplates: "Emails de décision jury",
        decisionDescription: "Un modèle par statut",
        decisionHint:
          "Statuts configurables : En attente, Validé, Sélectionné, Refusé, À revoir. Variable : {{filmTitle}}",
        finalRenderVia: "rendu final via",
        subject: "Objet",
        titleField: "Titre",
        body: "Corps",
        text: "Texte",
        html: "HTML",
        languageFr: "Français",
        languageEn: "Anglais",
        variablesHint: "Cliquer pour insérer",
        activeSubmissionTemplate: "Template soumission actif",
        activeDecisionTemplate: "Template décision actif",
        activeFieldRequired: "Cliquez d'abord un champ",
        unavailableForTemplate: "Non disponible pour ce template",
        insertToken: "Insérer",
        copy: "Copier",
        dynamicReplacedHint: "Remplacées dynamiquement à l'envoi de l'e-mail.",
        varGroups: {
          artist: "Artiste",
          festival: "Festival",
          film: "Film",
          submission: "Soumission",
          decision: "Décision",
        },
        varDescriptions: {
          artistName: "Nom complet de l'artiste",
          directorNameLegacy:
            "Nom réalisateur (compatibilité anciens templates)",
          festivalName: "Nom du festival",
          contactEmail: "Email de contact",
          filmTitle: "Titre du film",
          submissionId: "Identifiant unique du projet",
          submissionIdLegacy:
            "Identifiant soumission (compatibilité anciens templates)",
          submissionDate: "Date de soumission",
          decisionDate: "Date de la décision",
          stage: "Phase actuelle du festival",
        },
        statusShort: {
          pending: "En attente",
          validated: "Validé",
          selected: "Sélectionné",
          refused: "Refusé",
          review: "En révision",
        },
      },
      films: {
        chooseJury: "— Choisir un juré —",
        assignSuccess: "{{count}} film(s) assigné(s) avec succès",
        doubleClickHint:
          "Double-cliquez pour voir toutes les infos de la soumission",
        submitterModalTitle: "Détails de la soumission",
        tabFilm: "Film",
        tabContact: "Contact",
        tabAssets: "Fichiers & IA",
        tabLegal: "Légal",
        modalFilmId: "Film",
        modalFilmInfo: "Informations film",
        modalDirector: "Réalisateur",
        modalSubmittedAt: "Soumis le",
        modalCountryLang: "Pays · Langue",
        modalCategoryDuration: "Catégorie · Année · Durée",
        modalSynopsis: "Synopsis",
        modalSubmitter: "Soumissionnaire",
        modalEmail: "Email",
        modalPhone: "Téléphone",
        modalBirthdate: "Date de naissance",
        modalJob: "Métier",
        modalDiscovery: "Découverte du festival",
        modalAddress: "Adresse",
        modalSocials: "Réseaux sociaux",
        modalAssets: "Fichiers",
        modalVideo: "Vidéo",
        modalPoster: "Poster",
        modalSubtitles: "Sous-titres",
        modalOpen: "Ouvrir",
        modalOpenPlayer: "Ouvrir lecteur",
        modalCopy: "Copier le lien",
        modalCopied: "Copié",
        modalOpening: "Ouverture…",
        modalAssetUnavailable: "Aucun fichier disponible",
        modalVideoPreviewTitle: "Lecteur vidéo",
        modalAiTools: "Outils IA",
        modalSemanticTags: "Tags sémantiques",
        modalAIMeta: "IA & tags",
        modalMusicCredits: "Crédits musicaux",
        modalAdditional: "Informations complémentaires",
        modalLegalRef: "Référent légal",
        modalLegalRefEmail: "Email référent",
        modalConsents: "Consentements",
        modalConsentRules: "Règlement",
        modalConsentPromo: "Promotion",
        modalConsentNewsletter: "Newsletter",
        modalConsentCopyright: "Copyright",
        modalConsentRightsConfirmed: "Droits confirmés",
        sendEmail: "Envoyer email",
        sendingEmail: "Envoi…",
        commentsColumn: "Commentaires",
        pageInfo: "Page {{page}} / {{totalPages}}",
        noComment: "Aucun commentaire jury",
        viewComments: "Commentaires ({{count}})",
        commentsModalTitle: "Commentaires du jury",
        moreComments: "+{{count}} commentaire(s)",
        youtubeLink: "Lien YouTube",
        youtubeOnline: "En ligne",
        youtubePublic: "Lien public",
        youtubePrivate: "Lien privé",
        columns: {
          filmDirector: "Film · Réalisateur",
          countryDuration: "Pays · Durée",
          email: "E-mail",
        },
      },
      stats: {
        totalSubmissions: "Soumissions totales",
        unassigned: "Non assignés",
        countriesRepresented: "Pays représentés",
        totalJuryVotes: "Votes jury total",
      },
    },
    submit: {
      eyebrow: "Soumission · Courts-métrages IA",
      title: "Soumettre un film",
      titleLead: "SOUMETTRE",
      titleAccent: "UN FILM",
      subtitle: "Aucune inscription. Délai max : 2 minutes.",
      stepCounter: "ÉTAPE {{current}}/{{total}}",
      stepDirectorSheet: "FICHE RÉALISATEUR",
      stepFilmSheet: "FICHE FILM",
      stepDirector: "Auteure / Auteur",
      stepFilm: "Film",
      stepUploads: "Fichiers",
      stepConsents: "Consentements",
      stepDone: "Terminé",
      back: "← Précédent",
      next: "Étape suivante →",
      submit: "Soumettre le film",
      submitting: "Soumission en cours...",
      doneTitle: "Film reçu",
      doneText:
        "Votre film est bien enregistré. Un email de confirmation a été envoyé.",
      doneBadge: "SOUMISSION ENREGISTRÉE",
      doneSubmissionId: "Identifiant de soumission",
      doneEmailSentTo: "Email de confirmation envoyé à :",
      backHome: "Retour à l'accueil",
      submitAnother: "Soumettre un autre film",
      legalRefTitle: "RÉFÉRENT LÉGAL (obligatoire par film)",
      noEditHint:
        "Aucune modification possible après soumission · Les champs sont mémorisés sur cet appareil",
      tagsHint: '(en lien avec "Futurs souhaitables")',
      units: {
        mb: "Mo",
      },
      dropzone: {
        tooLarge: "Fichier trop lourd (max {{maxMb}} Mo)",
        invalidVideoType: "Fichier vidéo invalide (.mp4/.mov uniquement)",
        invalidPosterType: "Image invalide (JPG/PNG/GIF uniquement)",
        invalidSubtitlesType: "Sous-titres invalides (.srt/.vtt uniquement)",
        remove: "Supprimer",
        dropOrClick: "Glisser-déposer ou cliquer",
        maxMb: "max {{maxMb}} Mo",
      },
      uploads: {
        info: "> Votre vidéo sera stockée sur S3 Scaleway et uploadée en privé sur YouTube pour vérification copyright automatique. Aucune modification possible après soumission.",
        videoLabel: "Vidéo du film",
        videoHint: "Durée 1–2 min · Formats : .mp4 .mov · Max 300 Mo",
        posterLabel: "Poster / Affiche",
        posterHint: "Formats : JPG PNG GIF · Max 2 Mo · Ratio 16:9 recommandé",
        subtitlesLabel: "Sous-titres (optionnel)",
        subtitlesHint:
          "Formats : .srt .vtt · Langue natale et/ou anglais · Non requis si film muet/contemplatif",
        rules: {
          durationLabel: "Durée max",
          durationValue: "2 minutes",
          sizeLabel: "Taille max",
          sizeValue: "300 Mo",
          formatsLabel: "Formats",
          formatsValue: ".mp4 · .mov",
        },
      },
      summary: {
        title: "> RÉCAPITULATIF DE SOUMISSION",
        film: "Film",
        director: "Réalisateur",
        country: "Pays",
        duration: "Durée",
        category: "Catégorie",
        aiTools: "Outils IA",
        empty: "—",
      },
      consents: {
        rulesPrefix: "J'ai lu et j'accepte le",
        rulesLink: "règlement du festival marsAI 2026",
        rulesSuffix:
          "Je confirme que mon film respecte les conditions d'éligibilité (1–2 min, 100% IA générative).",
        promo:
          "J'autorise l'organisation marsAI (La Plateforme × Mobile Film Festival) à utiliser des extraits de mon film à des fins promotionnelles (réseaux sociaux, presse, site web) pendant la durée du festival.",
        copyright:
          "Je délègue les droits de diffusion de mon film à l'organisation marsAI pour la durée du festival (projection publique, mise en ligne sur la chaîne YouTube officielle marsAI).",
        newsletter:
          "J'accepte de recevoir la newsletter marsAI et les communications du festival (optionnel).",
      },
      warnings: {
        noEditPrefix:
          "Aucune modification ne sera possible après soumission. Un email de confirmation sera envoyé à",
        fallbackEmail: "votre adresse",
        noEditSuffix: ".",
        juryReview:
          "Votre film sera examiné par le jury international marsAI 2026.",
      },
      errors: {
        required: "Requis",
        requiredName: "Nom requis",
        invalidFullName: "Nom et prénom requis (min. 2 caractères chacun)",
        requiredEmail: "Email requis",
        invalidEmail: "Email invalide",
        requiredPhone: "Téléphone requis",
        invalidPhone: "Téléphone invalide",
        requiredBirthdate: "Date de naissance requise",
        mustBeAdult: "Vous devez avoir 18 ans révolus",
        requiredAddress: "Adresse requise",
        requiredZip: "Code postal requis",
        invalidZip: "Code postal invalide (chiffres uniquement)",
        requiredCity: "Ville requise",
        requiredCountry: "Pays requis",
        requiredJob: "Métier requis",
        requiredDiscovery: "Source de découverte requise",
        requiredLegalName: "Référent légal requis",
        requiredLegalEmail: "Email référent légal requis",
        requiredTitle: "Titre requis",
        requiredSynopsis: "Synopsis requis",
        requiredLanguage: "Langue requise",
        requiredCategory: "Catégorie requise",
        requiredDuration: "Durée requise",
        maxDuration: "Durée max 2 minutes",
        requiredAiTools: "Indiquez au moins un outil IA",
        requiredTags: "Sélectionnez au moins une thématique",
        requiredMusic: "Mentions musiques requises",
        requiredRights: "Confirmation des droits requise",
        requiredVideo: "Vidéo requise",
        requiredPoster: "Poster requis",
        consentsRequired:
          "> Les consentements obligatoires (marqués *) doivent être acceptés pour soumettre votre film.",
        submitFailed: "Soumission impossible",
        invalidServerResponse: "Réponse serveur invalide",
        unknown: "Erreur inconnue",
      },
      required: "requis",
      labels: {
        fullName: "Nom complet",
        email: "Email",
        phone: "Téléphone",
        birthdate: "Date de naissance",
        address: "Adresse",
        zip: "Code postal",
        city: "Ville",
        country: "Pays",
        job: "Métier actuel",
        discovery: "Comment avez-vous connu marsAI ?",
        socials: "Réseaux sociaux (optionnel)",
        additional: "Informations complémentaires (optionnel)",
        legalName: "Nom du référent légal",
        legalEmail: "Email du référent légal",
        title: "Titre du film",
        duration: "Durée exacte (ex: 1:30 ou 90)",
        synopsis: "Synopsis",
        countryProduction: "Pays de production",
        language: "Langue",
        category: "Catégorie",
        aiTools: "Outils IA",
        tags: "Tags sémantiques",
        music: "Mentions des musiques et sons",
      },
      placeholders: {
        name: "> Prénom Nom",
        email: "> email@domain.com",
        phone: "> +33 6 00 00 00 00",
        birthdate: "> Sélectionner une date",
        select: "Sélectionner...",
        address: "> Rue, numéro...",
        zip: "> 13000",
        city: "> Marseille",
        social: "@identifiant",
        additional: "> Notes, contexte de création...",
        title: "> Titre de votre court-métrage",
        synopsis: "> Décrivez votre film en quelques lignes...",
        duration: "> 1:30",
        otherTool: "> Autre outil IA non listé...",
        music:
          "> Ex: Musique générée par Suno AI. Sons : ElevenLabs + bibliothèque libre de droits.",
      },
      hints: {
        age: "> Vous devez avoir 18 ans révolus pour participer",
        durationMax: "> Durée max : 2 minutes (tolérance au-delà de 1 min)",
        synopsisMax: "(max 300 caractères)",
      },
      buttons: {
        add: "+ Ajouter",
      },
      defaults: {
        categories: [
          "Fiction",
          "Documentaire",
          "Expérimental",
          "Animation",
          "Poétique",
          "Contemplatif",
          "Autre",
        ],
        languages: FR_LANGUAGE_NAMES,
        countries: FR_COUNTRY_NAMES,
        jobs: [
          "Réalisateur·rice",
          "Artiste numérique",
          "Designer",
          "Développeur·se",
          "Étudiant·e",
          "Photographe",
          "Vidéaste",
          "Musicien·ne",
          "Autre",
        ],
        discoverySources: [
          "Réseaux sociaux (Instagram, TikTok…)",
          "Twitter / X",
          "LinkedIn",
          "Bouche à oreille",
          "Presse / Médias",
          "Newsletter",
          "La Plateforme",
          "Mobile Film Festival",
          "Moteur de recherche",
          "Autre",
        ],
        aiToolSuggestions: [
          "Sora",
          "MidJourney",
          "RunwayML",
          "Pika",
          "Kling",
          "DALL-E 3",
          "Stable Diffusion",
          "ElevenLabs",
          "Suno",
          "Udio",
          "MusicGen",
          "Luma AI",
          "Runway Gen-3",
          "HeyGen",
          "D-ID",
          "Synthesia",
          "Autre",
        ],
        semanticTags: [
          "Futur souhaitable",
          "Écologie",
          "Humanité & IA",
          "Solidarité",
          "Espoir",
          "Résilience",
          "Utopie",
          "Nature",
          "Paix",
          "Innovation sociale",
          "Diversité",
          "Éducation",
          "Santé",
          "Liberté",
          "Mémoire",
        ],
        socialNetworks: [
          { key: "instagram", label: "Instagram" },
          { key: "youtube", label: "YouTube" },
          { key: "linkedin", label: "LinkedIn" },
          { key: "x", label: "X / Twitter" },
          { key: "facebook", label: "Facebook" },
          { key: "tumblr", label: "Tumblr" },
        ],
      },
    },
  },
}.translation;
