// ========== FRENCH COUNTRIES ==========
const FR_COUNTRIES: Record<string, string> = {
  Afghanistan: "AF",
  Albanie: "AL",
  Algérie: "DZ",
  Andorre: "AD",
  Angola: "AO",
  "Antigua-et-Barbuda": "AG",
  "Arabie Saoudite": "SA",
  Arménie: "AM",
  Aruba: "AW",
  Australie: "AU",
  Autriche: "AT",
  Azerbaïdjan: "AZ",
  Bahamas: "BS",
  Bahreïn: "BH",
  Bangladesh: "BD",
  Barbade: "BB",
  Belgique: "BE",
  Belize: "BZ",
  Bénin: "BJ",
  Bermudes: "BM",
  Bhoutan: "BT",
  Biélorussie: "BY",
  Birmanie: "MM",
  Bolivie: "BO",
  "Bosnie-Herzégovine": "BA",
  Botswana: "BW",
  Brésil: "BR",
  Brunei: "BN",
  Bulgarie: "BG",
  "Burkina Faso": "BF",
  Burundi: "BI",
  Cambodge: "KH",
  Cameroun: "CM",
  Canada: "CA",
  "Cap-Vert": "CV",
  Chili: "CL",
  Chine: "CN",
  Chypre: "CY",
  Colombie: "CO",
  Comores: "KM",
  "Congo-Brazzaville": "CG",
  "Congo-Kinshasa": "CD",
  "Corée du Nord": "KP",
  "Corée du Sud": "KR",
  "Costa Rica": "CR",
  "Côte d'Ivoire": "CI",
  Croatie: "HR",
  Cuba: "CU",
  Curaçao: "CW",
  Danemark: "DK",
  Djibouti: "DJ",
  Dominique: "DM",
  Égypte: "EG",
  "Émirats Arabes Unis": "AE",
  Équateur: "EC",
  Érythrée: "ER",
  Espagne: "ES",
  Estonie: "EE",
  "États-Unis": "US",
  Eswatini: "SZ",
  Éthiopie: "ET",
  "Féd. de Micronésie": "FM",
  Fidji: "FJ",
  Finlande: "FI",
  France: "FR",
  Gabon: "GA",
  Gambie: "GM",
  Géorgie: "GE",
  Ghana: "GH",
  Gibraltar: "GI",
  Grèce: "GR",
  Grenade: "GD",
  Groenland: "GL",
  Guadeloupe: "GP",
  Guam: "GU",
  Guatemala: "GT",
  Guernesey: "GG",
  Guinée: "GN",
  "Guinée-Bissau": "GW",
  "Guinée équatoriale": "GQ",
  Guyana: "GY",
  "Guyane française": "GF",
  Haïti: "HT",
  Honduras: "HN",
  "Hong Kong": "HK",
  Hongrie: "HU",
  "Île Bouvet": "BV",
  "Île Christmas": "CX",
  "Île Norfolk": "NF",
  "Île de l'Ascension": "AC",
  "Îles Åland": "AX",
  "Îles Caïmans": "KY",
  "Îles Cocos": "CC",
  "Îles Féroé": "FO",
  "Îles Heard et McDonald": "HM",
  "Îles Malouines": "FK",
  "Îles Mariannes du Nord": "MP",
  "Îles Marshall": "MH",
  "Îles Pitcairn": "PN",
  "Îles Salomon": "SB",
  "Îles Turques et Caïques": "TC",
  "Îles Vierges britanniques": "VG",
  "Îles Vierges des États-Unis": "VI",
  "Île Maurice": "MU",
  Inde: "IN",
  Indonésie: "ID",
  Irak: "IQ",
  Iran: "IR",
  Irlande: "IE",
  Islande: "IS",
  Israël: "IL",
  Italie: "IT",
  Jamaïque: "JM",
  Japon: "JP",
  Jersey: "JE",
  Jordanie: "JO",
  Kazakhstan: "KZ",
  Kenya: "KE",
  Kirghizistan: "KG",
  Kiribati: "KI",
  Koweït: "KW",
  Laos: "LA",
  Lesotho: "LS",
  Lettonie: "LV",
  Liban: "LB",
  Liberia: "LR",
  Libye: "LY",
  Liechtenstein: "LI",
  Lituanie: "LT",
  Luxembourg: "LU",
  Macao: "MO",
  "Macédoine du Nord": "MK",
  Madagascar: "MG",
  Malaisie: "MY",
  Malawi: "MW",
  Maldives: "MV",
  Mali: "ML",
  Malte: "MT",
  Maroc: "MA",
  Martinique: "MQ",
  Mauritanie: "MR",
  Mayotte: "YT",
  Mexique: "MX",
  Moldavie: "MD",
  Monaco: "MC",
  Mongolie: "MN",
  Monténégro: "ME",
  Montserrat: "MS",
  Mozambique: "MZ",
  Namibie: "NA",
  Nauru: "NR",
  Népal: "NP",
  Nicaragua: "NI",
  Niger: "NE",
  Nigéria: "NG",
  Niue: "NU",
  "Nouvelle-Calédonie": "NC",
  "Nouvelle-Zélande": "NZ",
  Norvège: "NO",
  Oman: "OM",
  Ouganda: "UG",
  Ouzbékistan: "UZ",
  Pakistan: "PK",
  Palaos: "PW",
  Palestine: "PS",
  Panama: "PA",
  "Papouasie-Nouvelle-Guinée": "PG",
  Paraguay: "PY",
  "Pays-Bas": "NL",
  Pérou: "PE",
  Philippines: "PH",
  Pologne: "PL",
  "Polynésie française": "PF",
  "Porto Rico": "PR",
  Portugal: "PT",
  Qatar: "QA",
  "La Réunion": "RE",
  Roumanie: "RO",
  "Royaume-Uni": "GB",
  Russie: "RU",
  Rwanda: "RW",
  "Sahara occidental": "EH",
  "Saint-Barthélemy": "BL",
  "Saint-Marin": "SM",
  "Saint-Martin": "MF",
  "Saint-Pierre-et-Miquelon": "PM",
  "Saint-Vincent-et-les-Grenadines": "VC",
  "Sainte-Hélène": "SH",
  "Sainte-Lucie": "LC",
  Samoa: "WS",
  "Samoa américaines": "AS",
  "São Tomé-et-Príncipe": "ST",
  Sénégal: "SN",
  Serbie: "RS",
  Seychelles: "SC",
  "Sierra Leone": "SL",
  Singapour: "SG",
  "Sint Maarten": "SX",
  Slovaquie: "SK",
  Slovénie: "SI",
  Somalie: "SO",
  Soudan: "SD",
  "Soudan du Sud": "SS",
  "Sri Lanka": "LK",
  Suède: "SE",
  Suisse: "CH",
  Suriname: "SR",
  Svalbard: "SJ",
  Syrie: "SY",
  Tadjikistan: "TJ",
  Taïwan: "TW",
  Tanzanie: "TZ",
  Tchad: "TD",
  "Terres australes françaises": "TF",
  "Territoire britannique de l'océan Indien": "IO",
  Thaïlande: "TH",
  "Timor oriental": "TL",
  Togo: "TG",
  Tokelau: "TK",
  Tonga: "TO",
  "Trinité-et-Tobago": "TT",
  Tunisie: "TN",
  Turkménistan: "TM",
  Turquie: "TR",
  Tuvalu: "TV",
  Ukraine: "UA",
  Uruguay: "UY",
  Vanuatu: "VU",
  Vatican: "VA",
  Venezuela: "VE",
  Vietnam: "VN",
  "Wallis-et-Futuna": "WF",
  Yémen: "YE",
  Zambie: "ZM",
  Zimbabwe: "ZW",
};

// ========== ENGLISH COUNTRIES ==========
const EN_COUNTRIES: Record<string, string> = {
  Afghanistan: "AF",
  Albania: "AL",
  Algeria: "DZ",
  Andorra: "AD",
  Angola: "AO",
  "Antigua and Barbuda": "AG",
  "Saudi Arabia": "SA",
  Armenia: "AM",
  Aruba: "AW",
  Australia: "AU",
  Austria: "AT",
  Azerbaijan: "AZ",
  Bahamas: "BS",
  Bahrain: "BH",
  Bangladesh: "BD",
  Barbados: "BB",
  Belgium: "BE",
  Belize: "BZ",
  Benin: "BJ",
  Bermuda: "BM",
  Bhutan: "BT",
  Belarus: "BY",
  Myanmar: "MM",
  Bolivia: "BO",
  "Bosnia and Herzegovina": "BA",
  Botswana: "BW",
  Brazil: "BR",
  Brunei: "BN",
  Bulgaria: "BG",
  "Burkina Faso": "BF",
  Burundi: "BI",
  Cambodia: "KH",
  Cameroon: "CM",
  Canada: "CA",
  "Cape Verde": "CV",
  Chile: "CL",
  China: "CN",
  Cyprus: "CY",
  Colombia: "CO",
  Comoros: "KM",
  "Republic of the Congo": "CG",
  "Democratic Republic of the Congo": "CD",
  "North Korea": "KP",
  "South Korea": "KR",
  "Costa Rica": "CR",
  "Ivory Coast": "CI",
  Croatia: "HR",
  Cuba: "CU",
  Curaçao: "CW",
  Denmark: "DK",
  Djibouti: "DJ",
  Dominica: "DM",
  Egypt: "EG",
  "United Arab Emirates": "AE",
  Ecuador: "EC",
  Eritrea: "ER",
  Spain: "ES",
  Estonia: "EE",
  "United States": "US",
  Eswatini: "SZ",
  Ethiopia: "ET",
  "Federated States of Micronesia": "FM",
  Fiji: "FJ",
  Finland: "FI",
  France: "FR",
  Gabon: "GA",
  Gambia: "GM",
  Georgia: "GE",
  Ghana: "GH",
  Gibraltar: "GI",
  Greece: "GR",
  Grenada: "GD",
  Greenland: "GL",
  Guadeloupe: "GP",
  Guam: "GU",
  Guatemala: "GT",
  Guernsey: "GG",
  Guinea: "GN",
  "Guinea-Bissau": "GW",
  "Equatorial Guinea": "GQ",
  Guyana: "GY",
  "French Guiana": "GF",
  Haiti: "HT",
  Honduras: "HN",
  "Hong Kong": "HK",
  Hungary: "HU",
  "Bouvet Island": "BV",
  "Christmas Island": "CX",
  "Norfolk Island": "NF",
  "Ascension Island": "AC",
  "Åland Islands": "AX",
  "Cayman Islands": "KY",
  "Cocos Islands": "CC",
  "Faroe Islands": "FO",
  "Heard Island and McDonald Islands": "HM",
  "Falkland Islands": "FK",
  "Northern Mariana Islands": "MP",
  "Marshall Islands": "MH",
  "Pitcairn Islands": "PN",
  "Solomon Islands": "SB",
  "Turks and Caicos Islands": "TC",
  "British Virgin Islands": "VG",
  "U.S. Virgin Islands": "VI",
  Mauritius: "MU",
  India: "IN",
  Indonesia: "ID",
  Iraq: "IQ",
  Iran: "IR",
  Ireland: "IE",
  Iceland: "IS",
  Israel: "IL",
  Italy: "IT",
  Jamaica: "JM",
  Japan: "JP",
  Jersey: "JE",
  Jordan: "JO",
  Kazakhstan: "KZ",
  Kenya: "KE",
  Kyrgyzstan: "KG",
  Kiribati: "KI",
  Kuwait: "KW",
  Laos: "LA",
  Lesotho: "LS",
  Latvia: "LV",
  Lebanon: "LB",
  Liberia: "LR",
  Libya: "LY",
  Liechtenstein: "LI",
  Lithuania: "LT",
  Luxembourg: "LU",
  Macao: "MO",
  "North Macedonia": "MK",
  Madagascar: "MG",
  Malawi: "MW",
  Malaysia: "MY",
  Maldives: "MV",
  Mali: "ML",
  Malta: "MT",
  Morocco: "MA",
  Martinique: "MQ",
  Mauritania: "MR",
  Mayotte: "YT",
  Mexico: "MX",
  Moldova: "MD",
  Monaco: "MC",
  Mongolia: "MN",
  Montenegro: "ME",
  Montserrat: "MS",
  Mozambique: "MZ",
  Namibia: "NA",
  Nauru: "NR",
  Nepal: "NP",
  Nicaragua: "NI",
  Niger: "NE",
  Nigeria: "NG",
  Niue: "NU",
  "New Caledonia": "NC",
  "New Zealand": "NZ",
  Norway: "NO",
  Oman: "OM",
  Uganda: "UG",
  Uzbekistan: "UZ",
  Pakistan: "PK",
  Palau: "PW",
  Palestine: "PS",
  Panama: "PA",
  "Papua New Guinea": "PG",
  Paraguay: "PY",
  Netherlands: "NL",
  Peru: "PE",
  Philippines: "PH",
  Poland: "PL",
  "French Polynesia": "PF",
  "Puerto Rico": "PR",
  Portugal: "PT",
  Qatar: "QA",
  Réunion: "RE",
  Romania: "RO",
  "United Kingdom": "GB",
  Russia: "RU",
  Rwanda: "RW",
  "Western Sahara": "EH",
  "Saint Barthélemy": "BL",
  "San Marino": "SM",
  "Saint Martin": "MF",
  "Saint Pierre and Miquelon": "PM",
  "Saint Vincent and the Grenadines": "VC",
  "Saint Helena": "SH",
  "Saint Lucia": "LC",
  Samoa: "WS",
  "American Samoa": "AS",
  "São Tomé and Príncipe": "ST",
  Senegal: "SN",
  Serbia: "RS",
  Seychelles: "SC",
  "Sierra Leone": "SL",
  Singapore: "SG",
  "Sint Maarten": "SX",
  Slovakia: "SK",
  Slovenia: "SI",
  Somalia: "SO",
  Sudan: "SD",
  "South Sudan": "SS",
  "Sri Lanka": "LK",
  Sweden: "SE",
  Switzerland: "CH",
  Suriname: "SR",
  Svalbard: "SJ",
  Syria: "SY",
  Tajikistan: "TJ",
  Taiwan: "TW",
  Tanzania: "TZ",
  Chad: "TD",
  "French Southern Territories": "TF",
  "British Indian Ocean Territory": "IO",
  Thailand: "TH",
  "East Timor": "TL",
  Togo: "TG",
  Tokelau: "TK",
  Tonga: "TO",
  "Trinidad and Tobago": "TT",
  Tunisia: "TN",
  Turkmenistan: "TM",
  Turkey: "TR",
  Tuvalu: "TV",
  Ukraine: "UA",
  Uruguay: "UY",
  Vanuatu: "VU",
  "Vatican City": "VA",
  Venezuela: "VE",
  Vietnam: "VN",
  "Wallis and Futuna": "WF",
  Yemen: "YE",
  Zambia: "ZM",
  Zimbabwe: "ZW",
};

// Combine both for lookup
export const COUNTRY_CODES: Record<string, string> = {
  ...FR_COUNTRIES,
  ...EN_COUNTRIES,
};

export function getCountryCode(countryName: string): string | null {
  return COUNTRY_CODES[countryName] || null;
}
