export const COUNTRY_CODES: Record<string, string> = {
  // Français
  France: "FR",
  "États-Unis": "US",
  Japon: "JP",
  Brésil: "BR",
  Espagne: "ES",
  Allemagne: "DE",
  Italie: "IT",
  "Corée du Sud": "KR",
  Canada: "CA",
  Maroc: "MA",
  Argentine: "AR",
  Australie: "AU",
  Chine: "CN",
  Inde: "IN",
  Mexique: "MX",
  Portugal: "PT",
  "Pays-Bas": "NL",
  Belgique: "BE",
  Suisse: "CH",
  "Royaume-Uni": "GB",
  Suède: "SE",
  Norvège: "NO",
  Danemark: "DK",
  Finlande: "FI",
  Pologne: "PL",
  Autriche: "AT",
  Grèce: "GR",
  Irlande: "IE",
  Russie: "RU",
  Turquie: "TR",
  "Afrique du Sud": "ZA",
  Égypte: "EG",
  Tunisie: "TN",
  Algérie: "DZ",
  Sénégal: "SN",
  "Côte d'Ivoire": "CI",
  Nigéria: "NG",
  Kenya: "KE",
  Vietnam: "VN",
  Thaïlande: "TH",
  Indonésie: "ID",
  Malaisie: "MY",
  Singapour: "SG",
  Philippines: "PH",
  "Nouvelle-Zélande": "NZ",
  Chili: "CL",
  Colombie: "CO",
  Pérou: "PE",
  Venezuela: "VE",
  Ukraine: "UA",
  "Île de l'Ascension": "AC",

  // English
  "United States": "US",
  Japan: "JP",
  Brazil: "BR",
  Spain: "ES",
  Germany: "DE",
  Italy: "IT",
  "South Korea": "KR",
  Morocco: "MA",
  Argentina: "AR",
  Australia: "AU",
  China: "CN",
  India: "IN",
  Mexico: "MX",
  Netherlands: "NL",
  Belgium: "BE",
  Switzerland: "CH",
  "United Kingdom": "GB",
  Sweden: "SE",
  Norway: "NO",
  Denmark: "DK",
  Finland: "FI",
  Poland: "PL",
  Austria: "AT",
  Greece: "GR",
  Ireland: "IE",
  Russia: "RU",
  Turkey: "TR",
  "South Africa": "ZA",
  Egypt: "EG",
  Tunisia: "TN",
  Algeria: "DZ",
  Senegal: "SN",
  "Ivory Coast": "CI",
  Nigeria: "NG",
  Thailand: "TH",
  Indonesia: "ID",
  Malaysia: "MY",
  Singapore: "SG",
  "New Zealand": "NZ",
  Chile: "CL",
  Colombia: "CO",
  Peru: "PE",
  "Ascension Island": "AC",

  // Langue Pays FR
  Français: "FR",
  Anglais: "GB",
  Espagnol: "ES",
  Japonais: "JP",
  Portugais: "PT",
  Allemand: "DE",
  Italien: "IT",
  Mandarin: "CN",
  Arabe: "SA",
  Coréen: "KR",
  Russe: "RU",
  Hindi: "IN",
  // Langue Pays EN
  French: "FR",
  English: "GB",
  Spanish: "ES",
  Japanese: "JP",
  Portuguese: "PT",
  German: "DE",
  Italian: "IT",
  "Mandarin Chinese": "CN",
  Arabic: "SA",
  Korean: "KR",
  Russian: "RU",
};

export function getCountryCode(countryName: string): string | null {
  return COUNTRY_CODES[countryName] || null;
}
